### ISSUE TITLE
Logo Design Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [astellon/osc-crystal#1]
Hi @astellon  here's the logo design for this other project or yours! i hope you will like it too..
![OSC-CRTYSTAL-01](https://user-images.githubusercontent.com/36028424/55329439-25bbd980-54c1-11e9-953b-59aabf622f0c.png)

**Comment by astellon** [comment]
That's cool! I also like it!

I think the orange one suites this project (and it's my favorite color).

**Comment by Tobaloidee** [comment]
Same here..orange is my fave color..👍 will finalize the files again and send PR after..😃

**Comment by astellon** [comment]
l am looking forward to it!

**Comment by Tobaloidee** [comment]
Here's the PR #2 @astellon  also here is the [LINK](https://drive.google.com/drive/u/1/folders/1Gm3b6YbiX2Ys1o0-LgT1pDgplmnWQNSM) to the other versions and file formats. Thanks and my best regards to all your Projects! 

Im just here when you need a logo.. 
-Tobaloidee

**Comment by astellon** [comment]
Thank you many times! I'll work to merge soon.
